# This workflow builds a custom Debian installer ISO with Home Assistant integrated into it.
name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

permissions:
  contents: write

env:
  VERSION: 11.6.0

jobs:

#Kudos to aschmelyun for shortening my discovery on how to `docker run` in GitHub Actions:
#https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
#and to addnab for the action:
#https://github.com/marketplace/actions/docker-run-action

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build home-assistant ISO
        uses: addnab/docker-run-action@v3
        with:
          image: freshautomations/debian-builder:1.0.0
          options: -v ${{ github.workspace }}/home-assistant:/mnt -e VERSION=${{ env.VERSION }} -e NAME=home-assistant -e DEBUG=1
          run: /usr/bin/entrypoint.sh
      - name: Copy netinst ISO for quicker build of the next step
        run: cp home-assistant/debian-*-netinst.iso custom/ || echo "no ISO found"
      - name: Build custom ISO
        uses: addnab/docker-run-action@v3
        with:
          image: freshautomations/debian-builder:1.0.0
          options: -v ${{ github.workspace }}/custom:/mnt -e VERSION=${{ env.VERSION }} -e NAME=custom -e DEBUG=1 -e FORCE=1
          run: /usr/bin/entrypoint.sh
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            home-assistant/debian-*-home-assistant.iso
            custom/debian-*-custom.iso
